# services
services:
  nginx:
    build: ./nginx/
    image: nginx:web-page
    container_name: nginx
    init: true
    ports:
      - "80:80"
    volumes:
      - ../Web-Page:/var/www/html
    networks:
      - web-page

# networks
networks:
  web-page:
    name: web-page-network
    driver: bridge
